name: Deployment Pipeline

on:
  push:
    branches:
      - "test"
      - "master"
env:
  API_KEY: ${{ secrets.API_KEY }}
  MONGO_URI: $ {{ secrets.MONGO_URI}}
  JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: e2e test
        run: npm run e2e
      - name: unit test
        run: npm run test
