name: Deployment Pipeline

on:
  push:
    branches:
      - "test"
      - "master"
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          envkey_JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          envkey_JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          file_name: .env
          fail_on_empty: true

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Wait For Other Pipelines
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: otto-de/github-actions-wait@v1.0
        with:
          step-name: "Wait For Other Pipelines"
      - name: Install dependencies
        run: npm i
      - name: e2e test
        run: npm run e2e
      - name: unit test
        run: npm run test
