name: Deployment Pipeline

on:
  push:
    branches:
      - "test"
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: e2e test
        run: npm run e2e
        env:
          MONGO_URI: $ {{ secrets.MONGO_URI}}
          API_KEY: ${{ secrets.API_KEY }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      - name: unit test
        run: npm run test
